version: '3.8'

services:
  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    volumes:
      - ./weather_data.json:/app/weather_data.json
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 128M
          cpus: '0.25'

  transfer:
    build:
      context: .
      dockerfile: Dockerfile.transfer
    volumes:
      - ./weather_data.json:/app/weather_data.json
    restart: always
    depends_on:
      - parser
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 128M
          cpus: '0.25'
