version: '3.8'

services:
  weather_collector:
    build:
      context: .
      dockerfile: Dockerfile.parser
    volumes:
      - ./weather_data.json:/app/weather_data.json
    restart: always
    mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.3

  db_transfer:
    build:
      context: .
      dockerfile: Dockerfile.transfer
    volumes:
      - ./weather_data.json:/app/weather_data.json
    restart: always
    mem_limit: 300m
        mem_reservation: 100m
        cpus: 0.3
